import { Schema, model, models } from 'mongoose';
import { BOOKING_STATUSES, INDIAN_STATES_AND_UTS, ORDER_STATUSES, USER_ROLES, UNITS } from '../../../shared/src/domain.js';

const stateField = { type: String, enum: INDIAN_STATES_AND_UTS, required: true };
const userSchema = new Schema({ name: { type: String, required: true, trim: true }, email: { type: String, required: true, unique: true, lowercase: true }, passwordHash: { type: String, required: true }, role: { type: String, enum: USER_ROLES, required: true }, state: stateField, phone: String, village: String, district: String, address: String, aadhaarMasked: String, profilePhotoUrl: String, detectedLocation: String, bankAccountLast4: String, preferredLanguage: { type: String, default: 'English' } }, { timestamps: true });
const centreSchema = new Schema({ name: { type: String, required: true }, code: { type: String, required: true, unique: true }, state: stateField, district: String, address: String, dailyCapacityQuintals: Number, active: { type: Boolean, default: true }, categories: [String], procurementRates: [{ commodity: String, rate: Number }] }, { timestamps: true });
const harvestSchema = new Schema({ farmer: { type: Schema.Types.ObjectId, ref: 'User', required: true }, state: stateField, crop: { type: String, required: true }, variety: String, quantity: Number, unit: { type: String, enum: UNITS, default: 'quintal' }, available: { type: Boolean, default: true } }, { timestamps: true });
const cropSchema = new Schema({ distributor: { type: Schema.Types.ObjectId, ref: 'User', required: true }, state: stateField, name: { type: String, required: true }, variety: String, category: String, availableQuantity: Number, unit: { type: String, enum: UNITS, default: 'quintal' }, pricePerUnit: Number, imageUrl: String, active: { type: Boolean, default: true } }, { timestamps: true });
const bookingSchema = new Schema({ bookingNumber: { type: String, required: true, unique: true }, state: stateField, farmer: { type: Schema.Types.ObjectId, ref: 'User', required: true }, centre: { type: Schema.Types.ObjectId, ref: 'Centre', required: true }, crop: { type: String, required: true }, variety: String, estimatedQuantity: { type: Number, required: true }, unit: { type: String, enum: UNITS, default: 'quintal' }, appointmentDate: { type: Date, required: true }, queuePosition: Number, token: { type: String, required: true }, status: { type: String, enum: BOOKING_STATUSES, default: 'BOOKED' }, weighedQuantity: Number, acceptedQuantity: Number, procurementRate: Number, qualityGrade: String, qualityNote: String, failureReason: String, procurementValue: Number, paymentStatus: { type: String, enum: ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'], default: 'PENDING' }, transactionId: String, statusHistory: [{ status: String, note: String, changedBy: { type: Schema.Types.ObjectId, ref: 'User' }, changedAt: { type: Date, default: Date.now } }] }, { timestamps: true });
const orderSchema = new Schema({ orderNumber: { type: String, unique: true, required: true }, distributor: { type: Schema.Types.ObjectId, ref: 'User', required: true }, state: stateField, crop: { type: Schema.Types.ObjectId, ref: 'Crop', required: true }, requestedQuantity: Number, unit: { type: String, enum: UNITS, default: 'quintal' }, status: { type: String, enum: ORDER_STATUSES, default: 'NEW' }, paymentStatus: { type: String, enum: ['PENDING', 'PAID'], default: 'PENDING' }, history: [{ status: String, changedAt: { type: Date, default: Date.now } }] }, { timestamps: true });
const notificationSchema = new Schema({ user: { type: Schema.Types.ObjectId, ref: 'User', required: true }, state: stateField, title: String, message: String, read: { type: Boolean, default: false } }, { timestamps: true });
const procurementEventSchema = new Schema({ booking: { type: Schema.Types.ObjectId, ref: 'Booking', required: true }, state: stateField, status: { type: String, required: true }, note: String, changedBy: { type: Schema.Types.ObjectId, ref: 'User' } }, { timestamps: true });
const paymentSchema = new Schema({ booking: { type: Schema.Types.ObjectId, ref: 'Booking', required: true, unique: true }, farmer: { type: Schema.Types.ObjectId, ref: 'User', required: true }, state: stateField, amount: Number, status: { type: String, enum: ['PENDING', 'PROCESSING', 'COMPLETED'], default: 'PENDING' }, transactionId: String }, { timestamps: true });

export const User = models.User || model('User', userSchema);
export const Centre = models.Centre || model('Centre', centreSchema);
export const Harvest = models.Harvest || model('Harvest', harvestSchema);
export const Crop = models.Crop || model('Crop', cropSchema);
export const Booking = models.Booking || model('Booking', bookingSchema);
export const Order = models.Order || model('Order', orderSchema);
export const Notification = models.Notification || model('Notification', notificationSchema);
export const ProcurementEvent = models.ProcurementEvent || model('ProcurementEvent', procurementEventSchema);
export const Payment = models.Payment || model('Payment', paymentSchema);
